# Generated by Django 5.0.3 on 2024-04-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitbit", "0004_alter_fitbituser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitbituser",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fitbituser",
            name="scopes",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fitbituser",
            name="expires_in",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="FitbitNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("notification", models.TextField()),
                ("added", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitbit.fitbituser",
                    ),
                ),
            ],
        ),
    ]
