# make sure that the Django sample app
# starts up and runs

name: Django Sample App Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    # we just use sqlite
    # services:
    #   postgres:
    #     image: postgres:11
    #     env:
    #       POSTGRES_DB: testdb
    #       POSTGRES_USER: user
    #       POSTGRES_PASSWORD: password
    #     ports:
    #       - 5432:5432
    #     # Set health checks to wait until postgres has started
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        
    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test

    - name: Start server
      run: python manage.py runserver &
      
    # Verify the server is running, for example, 
    # by making a curl request to the dashboard
    - name: Verify server is running
      run: curl http://localhost:8000/
    
